#!/bin/sh

# policy
echo "-[Policy]---------------------------"
echo
echo -n "Add policy "
obj/tests/add_policy
/sbin/ip x p s
echo -n "Del policy "
obj/tests/del_policy
/sbin/ip x p s
echo

echo "-[State]----------------------------"
echo
# SA
echo -n "Add SA "
obj/tests/add_sa
/sbin/ip x s s
echo -n "Del SA "
obj/tests/del_sa
/sbin/ip x s s
echo

echo "-[Flush]----------------------------"
echo
echo -n "Add policy "
obj/tests/add_policy
/sbin/ip x p s
echo -n "Flush SPD "
obj/tests/flush_policies
echo
echo -n "Add SA "
obj/tests/add_sa
/sbin/ip x s s
echo -n "Flush SAD "
obj/tests/flush_states
echo
